/**
 * REST API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import * as models from './models';

export interface ExpenseDoc {
    content?: string;

    creditCard?: boolean;

    currency?: ExpenseDoc.CurrencyEnum;

    date?: Date;

    docId?: number;

    field?: string;

    issuer?: string;

    project?: string;

    reportId?: number;

    sum?: number;

    sumEur?: number;

}
export namespace ExpenseDoc {
    export enum CurrencyEnum {
        EEK = <any> 'EEK',
        EUR = <any> 'EUR',
        SEK = <any> 'SEK',
        USD = <any> 'USD',
        LVL = <any> 'LVL',
        TRY = <any> 'TRY',
        LTL = <any> 'LTL',
        CHF = <any> 'CHF',
        RUB = <any> 'RUB',
        GBP = <any> 'GBP'
    }
}
