/**
 * REST API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import * as models from './models';

export interface Report {
    creditSum?: number;

    documents?: Array<models.ExpenseDoc>;

    employee?: string;

    endDate?: Date;

    expenseSum?: number;

    reportId?: number;

    startDate?: Date;

    status?: Report.StatusEnum;

    totalSum?: number;

}
export namespace Report {
    export enum StatusEnum {
        Active = <any> 'Active',
        Confirmed = <any> 'Confirmed',
        Rejected = <any> 'Rejected'
    }
}
